/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gradient_cb.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_GtkGradient (void)
{
  GtkWidget *GtkGradient;
  GtkWidget *dialog_vbox1;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *Edit;
  GtkWidget *Close;

  GtkGradient = gtk_dialog_new ();
  gtk_widget_set_name (GtkGradient, "GtkGradient");
  gtk_object_set_data (GTK_OBJECT (GtkGradient), "GtkGradient", GtkGradient);
  gtk_window_set_title (GTK_WINDOW (GtkGradient), _("Gradient Selection"));
  gtk_window_set_modal (GTK_WINDOW (GtkGradient), TRUE);
  gtk_window_set_policy (GTK_WINDOW (GtkGradient), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (GtkGradient)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (GtkGradient), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  clist1 = gtk_clist_new (2);
  gtk_widget_set_name (clist1, "clist1");
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist1);
  gtk_widget_set_usize (clist1, -2, 130);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label1 = gtk_label_new (_("Gradient"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label1);

  label2 = gtk_label_new (_("Name"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label2);

  dialog_action_area1 = GTK_DIALOG (GtkGradient)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (GtkGradient), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  Edit = gtk_button_new_with_label (_("Edit"));
  gtk_widget_set_name (Edit, "Edit");
  gtk_widget_ref (Edit);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "Edit", Edit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Edit);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), Edit);
  GTK_WIDGET_SET_FLAGS (Edit, GTK_CAN_DEFAULT);

  Close = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (Close, "Close");
  gtk_widget_ref (Close);
  gtk_object_set_data_full (GTK_OBJECT (GtkGradient), "Close", Close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), Close);
  GTK_WIDGET_SET_FLAGS (Close, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (clist1), "select_row",
                      GTK_SIGNAL_FUNC (on_clist1_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Edit), "clicked",
                      GTK_SIGNAL_FUNC (on_Edit_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Close), "clicked",
                      GTK_SIGNAL_FUNC (on_Close_clicked),
                      NULL);

  return GtkGradient;
}

