/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fileselection1 (void);
GtkWidget* create_fontselectiondialog1 (void);
GtkWidget* create_colorselectiondialog1 (void);
GtkWidget* create_VerifyDialog (void);
