/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include <gtk/gtk.h>

#include "window3D.h"
#include "support.h"

int
main (int argc, char *argv[])
{ 
  GtkWidget *window3D;

#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, VIS5D_LOCALE_DIR);
  textdomain (PACKAGE);
#endif
  gtk_set_locale ();

  /* TODO: need to look for gtkrc file, currently we just look in 
	  the source dir since we don't install this version anyway
  */
  gtk_rc_add_default_file(VIS5D_SOURCE_DIR "/gtk/gtkrc");


  gtk_init (&argc, &argv);

  add_pixmap_directory (DATA_PREFIX "/pixmaps");
  add_pixmap_directory (VIS5D_SOURCE_DIR "/pixmaps");

  window3D = new_window3D(NULL);

  /* when we handle command line options we will change this */
  on_open1_activate(NULL, (gpointer) window3D);
  
  gtk_main ();
  return 0;
}



