/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "ProcedureDialog.h"
#include "PD_interface.h"
#include "support.h"

GtkWidget*
create_ProcedureDialog (void)
{
  GtkWidget *ProcedureDialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *scrolledwindow1;
  GtkWidget *ProcedureCtree;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *add;
  GtkWidget *delete;
  GtkWidget *close;

  ProcedureDialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (ProcedureDialog), "ProcedureDialog", ProcedureDialog);
  gtk_window_set_title (GTK_WINDOW (ProcedureDialog), _("Procedure"));
  GTK_WINDOW (ProcedureDialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_default_size (GTK_WINDOW (ProcedureDialog), -1, 250);
  gtk_window_set_policy (GTK_WINDOW (ProcedureDialog), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (ProcedureDialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (ProcedureDialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), scrolledwindow1, TRUE, TRUE, 0);

  ProcedureCtree = gtk_ctree_new (3, 0);
  gtk_widget_ref (ProcedureCtree);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "ProcedureCtree", ProcedureCtree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ProcedureCtree);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), ProcedureCtree);
  gtk_clist_set_column_width (GTK_CLIST (ProcedureCtree), 0, 113);
  gtk_clist_set_column_width (GTK_CLIST (ProcedureCtree), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (ProcedureCtree), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ProcedureCtree));

  label1 = gtk_label_new (_("Image Name"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_clist_set_column_widget (GTK_CLIST (ProcedureCtree), 0, label1);

  label2 = gtk_label_new (_("Graphic Type"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (ProcedureCtree), 1, label2);

  label3 = gtk_label_new (_("Variable"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (ProcedureCtree), 2, label3);

  dialog_action_area1 = GTK_DIALOG (ProcedureDialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (ProcedureDialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  add = gtk_button_new_with_label (_("Add\nImage"));
  gtk_widget_ref (add);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "add", add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), add);
  GTK_WIDGET_SET_FLAGS (add, GTK_CAN_DEFAULT);

  delete = gtk_button_new_with_label (_("Delete\nImage"));
  gtk_widget_ref (delete);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "delete", delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), delete);
  GTK_WIDGET_SET_FLAGS (delete, GTK_CAN_DEFAULT);

  close = gtk_button_new_with_label (_("Close"));
  gtk_widget_ref (close);
  gtk_object_set_data_full (GTK_OBJECT (ProcedureDialog), "close", close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), close);
  GTK_WIDGET_SET_FLAGS (close, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ProcedureCtree), "tree_select_row",
                      GTK_SIGNAL_FUNC (on_ProcedureCtree_tree_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ProcedureCtree), "tree_unselect_row",
                      GTK_SIGNAL_FUNC (on_ProcedureCtree_tree_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ProcedureCtree), "key_press_event",
                      GTK_SIGNAL_FUNC (on_ProcedureCtree_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ProcedureCtree), "tree_expand",
                      GTK_SIGNAL_FUNC (on_ProcedureCtree_tree_expand),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ProcedureCtree), "tree_collapse",
                      GTK_SIGNAL_FUNC (on_ProcedureCtree_tree_collapse),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (add), "clicked",
                      GTK_SIGNAL_FUNC (on_add_clicked),
                      ProcedureDialog);
  gtk_signal_connect (GTK_OBJECT (delete), "clicked",
                      GTK_SIGNAL_FUNC (on_delete_clicked),
                      ProcedureCtree);
  gtk_signal_connect (GTK_OBJECT (close), "clicked",
                      GTK_SIGNAL_FUNC (on_close_clicked),
                      ProcedureDialog);

  return ProcedureDialog;
}

