/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "textplot.h"
#include "tp_interface.h"
#include "support.h"

GtkWidget*
create_TextPlotDialog (void)
{
  GtkWidget *TextPlotDialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkObject *size_sb_adj;
  GtkWidget *size_sb;
  GtkObject *spacing_sb_adj;
  GtkWidget *spacing_sb;
  GtkObject *fontx_sb_adj;
  GtkWidget *fontx_sb;
  GtkObject *fonty_sb_adj;
  GtkWidget *fonty_sb;
  GtkWidget *Color;
  GtkWidget *label5;
  GtkWidget *textplot_variables;
  GtkWidget *textplot_variables_menu;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *tpclose;

  TextPlotDialog = gtk_dialog_new ();
  gtk_widget_set_name (TextPlotDialog, "TextPlotDialog");
  gtk_object_set_data (GTK_OBJECT (TextPlotDialog), "TextPlotDialog", TextPlotDialog);
  gtk_window_set_title (GTK_WINDOW (TextPlotDialog), _("Text Plot Dialog"));
  GTK_WINDOW (TextPlotDialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_policy (GTK_WINDOW (TextPlotDialog), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (TextPlotDialog)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (TextPlotDialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (6, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 3);

  label1 = gtk_label_new (_("Size:"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  label2 = gtk_label_new (_("Spacing:"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  label3 = gtk_label_new (_("Font Width:"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  label4 = gtk_label_new (_("Font Height:"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  size_sb_adj = gtk_adjustment_new (1, 0.01, 100, 1, 10, 10);
  size_sb = gtk_spin_button_new (GTK_ADJUSTMENT (size_sb_adj), 1, 2);
  gtk_widget_set_name (size_sb, "size_sb");
  gtk_widget_ref (size_sb);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "size_sb", size_sb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (size_sb);
  gtk_table_attach (GTK_TABLE (table1), size_sb, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (size_sb), TRUE);

  spacing_sb_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spacing_sb = gtk_spin_button_new (GTK_ADJUSTMENT (spacing_sb_adj), 1, 0);
  gtk_widget_set_name (spacing_sb, "spacing_sb");
  gtk_widget_ref (spacing_sb);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "spacing_sb", spacing_sb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spacing_sb);
  gtk_table_attach (GTK_TABLE (table1), spacing_sb, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  fontx_sb_adj = gtk_adjustment_new (10, 0, 100, 1, 10, 10);
  fontx_sb = gtk_spin_button_new (GTK_ADJUSTMENT (fontx_sb_adj), 1, 0);
  gtk_widget_set_name (fontx_sb, "fontx_sb");
  gtk_widget_ref (fontx_sb);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "fontx_sb", fontx_sb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fontx_sb);
  gtk_table_attach (GTK_TABLE (table1), fontx_sb, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  fonty_sb_adj = gtk_adjustment_new (10, 0, 100, 1, 10, 10);
  fonty_sb = gtk_spin_button_new (GTK_ADJUSTMENT (fonty_sb_adj), 1, 0);
  gtk_widget_set_name (fonty_sb, "fonty_sb");
  gtk_widget_ref (fonty_sb);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "fonty_sb", fonty_sb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fonty_sb);
  gtk_table_attach (GTK_TABLE (table1), fonty_sb, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Color = gtk_button_new_with_label (_("Color"));
  gtk_widget_set_name (Color, "Color");
  gtk_widget_ref (Color);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "Color", Color,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Color);
  gtk_table_attach (GTK_TABLE (table1), Color, 0, 2, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("Variable:"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  textplot_variables = gtk_option_menu_new ();
  gtk_widget_set_name (textplot_variables, "textplot_variables");
  gtk_widget_ref (textplot_variables);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "textplot_variables", textplot_variables,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textplot_variables);
  gtk_table_attach (GTK_TABLE (table1), textplot_variables, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (textplot_variables, 150, 40);
  gtk_container_set_border_width (GTK_CONTAINER (textplot_variables), 5);
  textplot_variables_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (textplot_variables), textplot_variables_menu);

  dialog_action_area1 = GTK_DIALOG (TextPlotDialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (TextPlotDialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  tpclose = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (tpclose, "tpclose");
  gtk_widget_ref (tpclose);
  gtk_object_set_data_full (GTK_OBJECT (TextPlotDialog), "tpclose", tpclose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tpclose);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), tpclose);
  GTK_WIDGET_SET_FLAGS (tpclose, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (size_sb), "changed",
                      GTK_SIGNAL_FUNC (on_tp_sb_changed),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (spacing_sb), "changed",
                      GTK_SIGNAL_FUNC (on_tp_sb_changed),
                      GINT_TO_POINTER(1));
  gtk_signal_connect (GTK_OBJECT (fontx_sb), "changed",
                      GTK_SIGNAL_FUNC (on_tp_sb_changed),
                      GINT_TO_POINTER(2));
  gtk_signal_connect (GTK_OBJECT (fonty_sb), "changed",
                      GTK_SIGNAL_FUNC (on_tp_sb_changed),
                      GINT_TO_POINTER(3));
  gtk_signal_connect (GTK_OBJECT (Color), "clicked",
                      GTK_SIGNAL_FUNC (on_Color_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (tpclose), "clicked",
                      GTK_SIGNAL_FUNC (on_tpclose_clicked),
                      NULL);

  return TextPlotDialog;
}

