/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "VarGraphicsControls.h"
#include "VGC_interface.h"
#include "support.h"

GtkWidget*
create_VarGraphicsControls (void)
{
  GtkWidget *VarGraphicsControls;
  GtkWidget *dialog_vbox8;
  GtkWidget *vbox22;
  GtkWidget *VarName;
  GtkWidget *hbox21;
  GtkWidget *toolbar1;
  GtkWidget *Hslicebutton;
  GtkWidget *Vslicebutton;
  GtkWidget *CHslicebutton;
  GtkWidget *CVslicebutton;
  GtkWidget *Isosurfbutton;
  GtkWidget *Volumebutton;
  GtkWidget *notebook3;
  GtkWidget *hbox22;
  GtkWidget *notebook2;
  GtkWidget *table8;
  GtkWidget *label65;
  GtkObject *hsmax_adj;
  GtkWidget *hsmax;
  GtkObject *hsinterval_adj;
  GtkWidget *hsinterval;
  GtkWidget *label102;
  GtkObject *hsmin_adj;
  GtkWidget *hsmin;
  GtkWidget *label66;
  GtkWidget *label72;
  GtkWidget *table9;
  GtkWidget *hs_colorselect;
  GtkWidget *label63;
  GtkWidget *toolbar2;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton5;
  GtkObject *linewidth_adj;
  GtkWidget *linewidth;
  GtkWidget *label62;
  GtkWidget *label73;
  GtkWidget *hsvbox;
  GtkWidget *label76;
  GtkWidget *hlevel_value;
  GtkWidget *hlevel_vscale;
  GtkWidget *label82;
  GtkWidget *hbox23;
  GtkWidget *table10;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkObject *chsmin_adj;
  GtkWidget *chsmin;
  GtkObject *chsmax_adj;
  GtkWidget *chsmax;
  GtkWidget *colortable_select;
  GtkWidget *label80;
  GtkWidget *fillstyle;
  GtkWidget *fillstyle_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *label69;
  GtkWidget *alpha;
  GtkWidget *hs_color_sample;
  GtkWidget *sample_label;
  GtkWidget *chvbox;
  GtkWidget *label88;
  GtkWidget *chlevel_value;
  GtkWidget *chlevel_vscale;
  GtkWidget *label83;
  GtkWidget *hbox25;
  GtkWidget *notebook4;
  GtkWidget *table14;
  GtkWidget *label104;
  GtkObject *vsmax_adj;
  GtkWidget *vsmax;
  GtkObject *vsinterval_adj;
  GtkWidget *vsinterval;
  GtkWidget *label105;
  GtkObject *vsmin_adj;
  GtkWidget *vsmin;
  GtkWidget *label106;
  GtkWidget *toolbar3;
  GtkWidget *vslice_move;
  GtkWidget *label97;
  GtkWidget *table13;
  GtkWidget *button4;
  GtkWidget *label98;
  GtkWidget *optionmenu2;
  GtkWidget *optionmenu2_menu;
  GtkWidget *label99;
  GtkWidget *optionmenu3;
  GtkWidget *optionmenu3_menu;
  GtkWidget *label100;
  GtkWidget *label84;
  GtkWidget *hbox24;
  GtkWidget *table11;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *button3;
  GtkWidget *label92;
  GtkWidget *optionmenu1;
  GtkWidget *optionmenu1_menu;
  GtkWidget *label93;
  GtkWidget *hscale1;
  GtkWidget *label85;
  GtkWidget *hbox26;
  GtkWidget *vbox24;
  GtkWidget *label101;
  GtkWidget *isolevel;
  GtkWidget *label86;
  GtkWidget *empty_notebook_page;
  GtkWidget *label87;
  GtkWidget *dialog_action_area8;
  GtkWidget *hbuttonbox3;
  GtkWidget *hsliceclear;
  GtkWidget *hsclose;

  VarGraphicsControls = gtk_dialog_new ();
  gtk_widget_set_name (VarGraphicsControls, "VarGraphicsControls");
  gtk_object_set_data (GTK_OBJECT (VarGraphicsControls), "VarGraphicsControls", VarGraphicsControls);
  gtk_window_set_title (GTK_WINDOW (VarGraphicsControls), _("Vis5d+ Variable Graphics Controls"));
  GTK_WINDOW (VarGraphicsControls)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_policy (GTK_WINDOW (VarGraphicsControls), TRUE, TRUE, FALSE);

  dialog_vbox8 = GTK_DIALOG (VarGraphicsControls)->vbox;
  gtk_widget_set_name (dialog_vbox8, "dialog_vbox8");
  gtk_object_set_data (GTK_OBJECT (VarGraphicsControls), "dialog_vbox8", dialog_vbox8);
  gtk_widget_show (dialog_vbox8);

  vbox22 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox22, "vbox22");
  gtk_widget_ref (vbox22);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "vbox22", vbox22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox22);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), vbox22, TRUE, TRUE, 0);

  VarName = gtk_label_new ("");
  gtk_widget_set_name (VarName, "VarName");
  gtk_widget_ref (VarName);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "VarName", VarName,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (VarName);
  gtk_box_pack_start (GTK_BOX (vbox22), VarName, FALSE, FALSE, 0);

  hbox21 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox21, "hbox21");
  gtk_widget_ref (hbox21);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbox21", hbox21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox22), hbox21, TRUE, TRUE, 0);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_VERTICAL, GTK_TOOLBAR_TEXT);
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox21), toolbar1, FALSE, FALSE, 0);

  Hslicebutton = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Horizontal\nIsolines"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (Hslicebutton, "Hslicebutton");
  gtk_widget_ref (Hslicebutton);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "Hslicebutton", Hslicebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Hslicebutton);

  Vslicebutton = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Vertical\nIsolines"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (Vslicebutton, "Vslicebutton");
  gtk_widget_ref (Vslicebutton);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "Vslicebutton", Vslicebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Vslicebutton);
  gtk_widget_set_sensitive (Vslicebutton, FALSE);

  CHslicebutton = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Horizontal\nContours"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (CHslicebutton, "CHslicebutton");
  gtk_widget_ref (CHslicebutton);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "CHslicebutton", CHslicebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (CHslicebutton);

  CVslicebutton = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Vertical\nContours"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (CVslicebutton, "CVslicebutton");
  gtk_widget_ref (CVslicebutton);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "CVslicebutton", CVslicebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (CVslicebutton);
  gtk_widget_set_sensitive (CVslicebutton, FALSE);

  Isosurfbutton = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Isosurface\n"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (Isosurfbutton, "Isosurfbutton");
  gtk_widget_ref (Isosurfbutton);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "Isosurfbutton", Isosurfbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Isosurfbutton);
  gtk_widget_set_sensitive (Isosurfbutton, FALSE);

  Volumebutton = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Volume\n"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (Volumebutton, "Volumebutton");
  gtk_widget_ref (Volumebutton);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "Volumebutton", Volumebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Volumebutton);
  gtk_widget_set_sensitive (Volumebutton, FALSE);

  notebook3 = gtk_notebook_new ();
  gtk_widget_set_name (notebook3, "notebook3");
  gtk_widget_ref (notebook3);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "notebook3", notebook3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook3);
  gtk_box_pack_start (GTK_BOX (hbox21), notebook3, TRUE, TRUE, 0);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox22, "hbox22");
  gtk_widget_ref (hbox22);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbox22", hbox22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (notebook3), hbox22);

  notebook2 = gtk_notebook_new ();
  gtk_widget_set_name (notebook2, "notebook2");
  gtk_widget_ref (notebook2);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "notebook2", notebook2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (hbox22), notebook2, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook2), GTK_POS_LEFT);

  table8 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table8, "table8");
  gtk_widget_ref (table8);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "table8", table8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (notebook2), table8);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 10);

  label65 = gtk_label_new (_("Minimum:"));
  gtk_widget_set_name (label65, "label65");
  gtk_widget_ref (label65);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label65", label65,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table8), label65, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label65), 10, 0);

  hsmax_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  hsmax = gtk_spin_button_new (GTK_ADJUSTMENT (hsmax_adj), 1, 3);
  gtk_widget_set_name (hsmax, "hsmax");
  gtk_widget_ref (hsmax);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hsmax", hsmax,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsmax);
  gtk_table_attach (GTK_TABLE (table8), hsmax, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (hsmax, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (hsmax), TRUE);

  hsinterval_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  hsinterval = gtk_spin_button_new (GTK_ADJUSTMENT (hsinterval_adj), 1, 3);
  gtk_widget_set_name (hsinterval, "hsinterval");
  gtk_widget_ref (hsinterval);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hsinterval", hsinterval,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsinterval);
  gtk_table_attach (GTK_TABLE (table8), hsinterval, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (hsinterval, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (hsinterval), TRUE);

  label102 = gtk_label_new (_("Interval:"));
  gtk_widget_set_name (label102, "label102");
  gtk_widget_ref (label102);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label102", label102,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label102);
  gtk_table_attach (GTK_TABLE (table8), label102, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label102), 0, 0.5);

  hsmin_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  hsmin = gtk_spin_button_new (GTK_ADJUSTMENT (hsmin_adj), 1, 3);
  gtk_widget_set_name (hsmin, "hsmin");
  gtk_widget_ref (hsmin);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hsmin", hsmin,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsmin);
  gtk_table_attach (GTK_TABLE (table8), hsmin, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (hsmin, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (hsmin), TRUE);

  label66 = gtk_label_new (_("Maximum:"));
  gtk_widget_set_name (label66, "label66");
  gtk_widget_ref (label66);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label66", label66,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table8), label66, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label66), 10, 0);

  label72 = gtk_label_new (_("Settings"));
  gtk_widget_set_name (label72, "label72");
  gtk_widget_ref (label72);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label72", label72,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label72);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label72);

  table9 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table9, "table9");
  gtk_widget_ref (table9);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "table9", table9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (notebook2), table9);

  hs_colorselect = gtk_button_new_with_label (_("Select Color"));
  gtk_widget_set_name (hs_colorselect, "hs_colorselect");
  gtk_widget_ref (hs_colorselect);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hs_colorselect", hs_colorselect,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hs_colorselect);
  gtk_table_attach (GTK_TABLE (table9), hs_colorselect, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label63 = gtk_label_new (_("Line Width:"));
  gtk_widget_set_name (label63, "label63");
  gtk_widget_ref (label63);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label63", label63,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table9), label63, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label63), 10, 0);

  toolbar2 = gtk_toolbar_new (GTK_ORIENTATION_VERTICAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (toolbar2, "toolbar2");
  gtk_widget_ref (toolbar2);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "toolbar2", toolbar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar2);
  gtk_table_attach (GTK_TABLE (table9), toolbar2, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tmp_toolbar_icon = create_pixmap (VarGraphicsControls, "solid_line.xpm");
  radiobutton1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_RADIOBUTTON,
                                NULL,
                                _("radiobutton1"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (radiobutton1, "radiobutton1");
  gtk_widget_ref (radiobutton1);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "radiobutton1", radiobutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton1);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (radiobutton1), FALSE);

  tmp_toolbar_icon = create_pixmap (VarGraphicsControls, "dashed_line.xpm");
  radiobutton2 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_RADIOBUTTON,
                                radiobutton1,
                                _("radiobutton2"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (radiobutton2, "radiobutton2");
  gtk_widget_ref (radiobutton2);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "radiobutton2", radiobutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton2);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (radiobutton2), FALSE);

  tmp_toolbar_icon = create_pixmap (VarGraphicsControls, "dotted_line.xpm");
  radiobutton3 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_RADIOBUTTON,
                                radiobutton1,
                                _("radiobutton3"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (radiobutton3, "radiobutton3");
  gtk_widget_ref (radiobutton3);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "radiobutton3", radiobutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton3);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (radiobutton3), FALSE);

  tmp_toolbar_icon = create_pixmap (VarGraphicsControls, "dot_dashed_line.xpm");
  radiobutton5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_RADIOBUTTON,
                                radiobutton1,
                                _("radiobutton5"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (radiobutton5, "radiobutton5");
  gtk_widget_ref (radiobutton5);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "radiobutton5", radiobutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton5);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (radiobutton5), FALSE);

  linewidth_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  linewidth = gtk_spin_button_new (GTK_ADJUSTMENT (linewidth_adj), 1, 0);
  gtk_widget_set_name (linewidth, "linewidth");
  gtk_widget_ref (linewidth);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "linewidth", linewidth,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (linewidth);
  gtk_table_attach (GTK_TABLE (table9), linewidth, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (linewidth), TRUE);

  label62 = gtk_label_new (_("Line Style:"));
  gtk_widget_set_name (label62, "label62");
  gtk_widget_ref (label62);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label62", label62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table9), label62, 0, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label62), 10, 0);

  label73 = gtk_label_new (_("Style"));
  gtk_widget_set_name (label73, "label73");
  gtk_widget_ref (label73);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label73", label73,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label73);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label73);

  hsvbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (hsvbox, "hsvbox");
  gtk_widget_ref (hsvbox);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hsvbox", hsvbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsvbox);
  gtk_box_pack_start (GTK_BOX (hbox22), hsvbox, TRUE, TRUE, 0);

  label76 = gtk_label_new (_("Level"));
  gtk_widget_set_name (label76, "label76");
  gtk_widget_ref (label76);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label76", label76,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hsvbox), label76, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label76), 5, 5);

  hlevel_value = gtk_label_new ("");
  gtk_widget_set_name (hlevel_value, "hlevel_value");
  gtk_widget_ref (hlevel_value);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hlevel_value", hlevel_value,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hlevel_value);
  gtk_box_pack_start (GTK_BOX (hsvbox), hlevel_value, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (hlevel_value), 5, 5);

  hlevel_vscale = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1000, 1, 0, 0)));
  gtk_widget_set_name (hlevel_vscale, "hlevel_vscale");
  gtk_widget_ref (hlevel_vscale);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hlevel_vscale", hlevel_vscale,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hlevel_vscale);
  gtk_box_pack_start (GTK_BOX (hsvbox), hlevel_vscale, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hlevel_vscale), FALSE);

  label82 = gtk_label_new (_("HI"));
  gtk_widget_set_name (label82, "label82");
  gtk_widget_ref (label82);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label82", label82,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label82);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label82);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox23, "hbox23");
  gtk_widget_ref (hbox23);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbox23", hbox23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (notebook3), hbox23);

  table10 = gtk_table_new (7, 2, FALSE);
  gtk_widget_set_name (table10, "table10");
  gtk_widget_ref (table10);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "table10", table10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table10);
  gtk_box_pack_start (GTK_BOX (hbox23), table10, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table10), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table10), 5);

  label78 = gtk_label_new (_("Minimum:"));
  gtk_widget_set_name (label78, "label78");
  gtk_widget_ref (label78);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label78", label78,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label78);
  gtk_table_attach (GTK_TABLE (table10), label78, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label78), 10, 0);

  label79 = gtk_label_new (_("Maximum:"));
  gtk_widget_set_name (label79, "label79");
  gtk_widget_ref (label79);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label79", label79,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label79);
  gtk_table_attach (GTK_TABLE (table10), label79, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label79), 10, 0);

  chsmin_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  chsmin = gtk_spin_button_new (GTK_ADJUSTMENT (chsmin_adj), 1, 3);
  gtk_widget_set_name (chsmin, "chsmin");
  gtk_widget_ref (chsmin);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "chsmin", chsmin,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (chsmin);
  gtk_table_attach (GTK_TABLE (table10), chsmin, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (chsmin, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (chsmin), TRUE);

  chsmax_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  chsmax = gtk_spin_button_new (GTK_ADJUSTMENT (chsmax_adj), 1, 3);
  gtk_widget_set_name (chsmax, "chsmax");
  gtk_widget_ref (chsmax);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "chsmax", chsmax,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (chsmax);
  gtk_table_attach (GTK_TABLE (table10), chsmax, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (chsmax, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (chsmax), TRUE);

  colortable_select = gtk_button_new_with_label (_("Select ColorTable"));
  gtk_widget_set_name (colortable_select, "colortable_select");
  gtk_widget_ref (colortable_select);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "colortable_select", colortable_select,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (colortable_select);
  gtk_table_attach (GTK_TABLE (table10), colortable_select, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label80 = gtk_label_new (_("Polygon \nFill Style"));
  gtk_widget_set_name (label80, "label80");
  gtk_widget_ref (label80);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label80", label80,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label80);
  gtk_table_attach (GTK_TABLE (table10), label80, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label80), 5, 0);

  fillstyle = gtk_option_menu_new ();
  gtk_widget_set_name (fillstyle, "fillstyle");
  gtk_widget_ref (fillstyle);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "fillstyle", fillstyle,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fillstyle);
  gtk_table_attach (GTK_TABLE (table10), fillstyle, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  fillstyle_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Fill"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (fillstyle_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Lines"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (fillstyle_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Points"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (fillstyle_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (fillstyle), fillstyle_menu);

  label69 = gtk_label_new (_("Alpha:"));
  gtk_widget_set_name (label69, "label69");
  gtk_widget_ref (label69);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label69", label69,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label69);
  gtk_table_attach (GTK_TABLE (table10), label69, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label69), 0, 2.98023e-08);
  gtk_misc_set_padding (GTK_MISC (label69), 5, 0);

  alpha = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 0, 1, 0.05, 0, 0)));
  gtk_widget_set_name (alpha, "alpha");
  gtk_widget_ref (alpha);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "alpha", alpha,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alpha);
  gtk_table_attach (GTK_TABLE (table10), alpha, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (alpha), 2);

  hs_color_sample = gtk_preview_new (GTK_PREVIEW_COLOR);
  gtk_widget_set_name (hs_color_sample, "hs_color_sample");
  gtk_widget_ref (hs_color_sample);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hs_color_sample", hs_color_sample,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hs_color_sample);
  gtk_table_attach (GTK_TABLE (table10), hs_color_sample, 0, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_preview_set_expand (GTK_PREVIEW (hs_color_sample), TRUE);

  sample_label = gtk_label_new ("");
  gtk_widget_set_name (sample_label, "sample_label");
  gtk_widget_ref (sample_label);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "sample_label", sample_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sample_label);
  gtk_table_attach (GTK_TABLE (table10), sample_label, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (sample_label), 0, 0.5);

  chvbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (chvbox, "chvbox");
  gtk_widget_ref (chvbox);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "chvbox", chvbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (chvbox);
  gtk_box_pack_start (GTK_BOX (hbox23), chvbox, TRUE, TRUE, 0);

  label88 = gtk_label_new (_("Level"));
  gtk_widget_set_name (label88, "label88");
  gtk_widget_ref (label88);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label88", label88,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (chvbox), label88, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label88), 5, 5);

  chlevel_value = gtk_label_new ("");
  gtk_widget_set_name (chlevel_value, "chlevel_value");
  gtk_widget_ref (chlevel_value);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "chlevel_value", chlevel_value,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (chlevel_value);
  gtk_box_pack_start (GTK_BOX (chvbox), chlevel_value, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (chlevel_value), 5, 5);

  chlevel_vscale = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1000, 1, 0, 0)));
  gtk_widget_set_name (chlevel_vscale, "chlevel_vscale");
  gtk_widget_ref (chlevel_vscale);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "chlevel_vscale", chlevel_vscale,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (chlevel_vscale);
  gtk_box_pack_start (GTK_BOX (chvbox), chlevel_vscale, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (chlevel_vscale), FALSE);

  label83 = gtk_label_new (_("HC"));
  gtk_widget_set_name (label83, "label83");
  gtk_widget_ref (label83);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label83", label83,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label83);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label83);

  hbox25 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox25, "hbox25");
  gtk_widget_ref (hbox25);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbox25", hbox25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (notebook3), hbox25);

  notebook4 = gtk_notebook_new ();
  gtk_widget_set_name (notebook4, "notebook4");
  gtk_widget_ref (notebook4);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "notebook4", notebook4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook4);
  gtk_box_pack_start (GTK_BOX (hbox25), notebook4, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook4), GTK_POS_LEFT);

  table14 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table14, "table14");
  gtk_widget_ref (table14);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "table14", table14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table14);
  gtk_container_add (GTK_CONTAINER (notebook4), table14);
  gtk_table_set_row_spacings (GTK_TABLE (table14), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table14), 10);

  label104 = gtk_label_new (_("Minimum:"));
  gtk_widget_set_name (label104, "label104");
  gtk_widget_ref (label104);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label104", label104,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label104);
  gtk_table_attach (GTK_TABLE (table14), label104, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label104), 10, 0);

  vsmax_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  vsmax = gtk_spin_button_new (GTK_ADJUSTMENT (vsmax_adj), 1, 3);
  gtk_widget_set_name (vsmax, "vsmax");
  gtk_widget_ref (vsmax);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "vsmax", vsmax,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vsmax);
  gtk_table_attach (GTK_TABLE (table14), vsmax, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (vsmax), TRUE);

  vsinterval_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  vsinterval = gtk_spin_button_new (GTK_ADJUSTMENT (vsinterval_adj), 1, 3);
  gtk_widget_set_name (vsinterval, "vsinterval");
  gtk_widget_ref (vsinterval);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "vsinterval", vsinterval,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vsinterval);
  gtk_table_attach (GTK_TABLE (table14), vsinterval, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (vsinterval), TRUE);

  label105 = gtk_label_new (_("Interval:"));
  gtk_widget_set_name (label105, "label105");
  gtk_widget_ref (label105);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label105", label105,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label105);
  gtk_table_attach (GTK_TABLE (table14), label105, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label105), 0, 0.5);

  vsmin_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  vsmin = gtk_spin_button_new (GTK_ADJUSTMENT (vsmin_adj), 1, 3);
  gtk_widget_set_name (vsmin, "vsmin");
  gtk_widget_ref (vsmin);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "vsmin", vsmin,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vsmin);
  gtk_table_attach (GTK_TABLE (table14), vsmin, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (vsmin), TRUE);

  label106 = gtk_label_new (_("Maximum:"));
  gtk_widget_set_name (label106, "label106");
  gtk_widget_ref (label106);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label106", label106,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label106);
  gtk_table_attach (GTK_TABLE (table14), label106, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label106), 10, 0);

  toolbar3 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (toolbar3, "toolbar3");
  gtk_widget_ref (toolbar3);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "toolbar3", toolbar3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar3);
  gtk_table_attach (GTK_TABLE (table14), toolbar3, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  vslice_move = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Move Slice"),
                                _("Move Slice"), NULL,
                                NULL, NULL, NULL);
  gtk_widget_set_name (vslice_move, "vslice_move");
  gtk_widget_ref (vslice_move);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "vslice_move", vslice_move,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vslice_move);

  label97 = gtk_label_new (_("Settings"));
  gtk_widget_set_name (label97, "label97");
  gtk_widget_ref (label97);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label97", label97,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label97);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label97);

  table13 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table13, "table13");
  gtk_widget_ref (table13);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "table13", table13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table13);
  gtk_container_add (GTK_CONTAINER (notebook4), table13);

  button4 = gtk_button_new_with_label (_("Select Color"));
  gtk_widget_set_name (button4, "button4");
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_table_attach (GTK_TABLE (table13), button4, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label98 = gtk_label_new (_("Line Style:"));
  gtk_widget_set_name (label98, "label98");
  gtk_widget_ref (label98);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label98", label98,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_table_attach (GTK_TABLE (table13), label98, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (label98, FALSE);
  gtk_misc_set_padding (GTK_MISC (label98), 10, 0);

  optionmenu2 = gtk_option_menu_new ();
  gtk_widget_set_name (optionmenu2, "optionmenu2");
  gtk_widget_ref (optionmenu2);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "optionmenu2", optionmenu2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_table_attach (GTK_TABLE (table13), optionmenu2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (optionmenu2, FALSE);
  optionmenu2_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Solid"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu2), optionmenu2_menu);

  label99 = gtk_label_new (_("Line Width:"));
  gtk_widget_set_name (label99, "label99");
  gtk_widget_ref (label99);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label99", label99,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label99);
  gtk_table_attach (GTK_TABLE (table13), label99, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label99), 10, 0);

  optionmenu3 = gtk_option_menu_new ();
  gtk_widget_set_name (optionmenu3, "optionmenu3");
  gtk_widget_ref (optionmenu3);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "optionmenu3", optionmenu3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (optionmenu3);
  gtk_table_attach (GTK_TABLE (table13), optionmenu3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  optionmenu3_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu3_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu3_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("3"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu3_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("4"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu3_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("5"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu3_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu3), optionmenu3_menu);

  label100 = gtk_label_new (_("Style"));
  gtk_widget_set_name (label100, "label100");
  gtk_widget_ref (label100);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label100", label100,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label100);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label100);

  label84 = gtk_label_new (_("VI"));
  gtk_widget_set_name (label84, "label84");
  gtk_widget_ref (label84);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label84", label84,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label84);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label84);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox24, "hbox24");
  gtk_widget_ref (hbox24);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbox24", hbox24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (notebook3), hbox24);

  table11 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table11, "table11");
  gtk_widget_ref (table11);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "table11", table11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table11);
  gtk_box_pack_start (GTK_BOX (hbox24), table11, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table11), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table11), 5);

  label90 = gtk_label_new (_("Minimum:"));
  gtk_widget_set_name (label90, "label90");
  gtk_widget_ref (label90);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label90", label90,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label90);
  gtk_table_attach (GTK_TABLE (table11), label90, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label90), 10, 0);

  label91 = gtk_label_new (_("Maximum:"));
  gtk_widget_set_name (label91, "label91");
  gtk_widget_ref (label91);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label91", label91,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label91);
  gtk_table_attach (GTK_TABLE (table11), label91, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label91), 10, 0);

  spinbutton1_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 3);
  gtk_widget_set_name (spinbutton1, "spinbutton1");
  gtk_widget_ref (spinbutton1);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "spinbutton1", spinbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton1);
  gtk_table_attach (GTK_TABLE (table11), spinbutton1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton1), TRUE);

  spinbutton2_adj = gtk_adjustment_new (1, -65536, 65536, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 3);
  gtk_widget_set_name (spinbutton2, "spinbutton2");
  gtk_widget_ref (spinbutton2);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "spinbutton2", spinbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton2);
  gtk_table_attach (GTK_TABLE (table11), spinbutton2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton2), TRUE);

  button3 = gtk_button_new_with_label (_("Select ColorTable"));
  gtk_widget_set_name (button3, "button3");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_table_attach (GTK_TABLE (table11), button3, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label92 = gtk_label_new (_("Polygon \nFill Style"));
  gtk_widget_set_name (label92, "label92");
  gtk_widget_ref (label92);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label92", label92,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label92);
  gtk_table_attach (GTK_TABLE (table11), label92, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label92), 5, 0);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_set_name (optionmenu1, "optionmenu1");
  gtk_widget_ref (optionmenu1);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "optionmenu1", optionmenu1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (optionmenu1);
  gtk_table_attach (GTK_TABLE (table11), optionmenu1, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  optionmenu1_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Fill"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Lines"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Points"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), optionmenu1_menu);

  label93 = gtk_label_new (_("Alpha:"));
  gtk_widget_set_name (label93, "label93");
  gtk_widget_ref (label93);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label93", label93,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label93);
  gtk_table_attach (GTK_TABLE (table11), label93, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label93), 0, 2.98023e-08);
  gtk_misc_set_padding (GTK_MISC (label93), 5, 0);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 0, 1, 0.05, 0, 0)));
  gtk_widget_set_name (hscale1, "hscale1");
  gtk_widget_ref (hscale1);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hscale1", hscale1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale1);
  gtk_table_attach (GTK_TABLE (table11), hscale1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (hscale1), 2);

  label85 = gtk_label_new (_("VC"));
  gtk_widget_set_name (label85, "label85");
  gtk_widget_ref (label85);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label85", label85,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label85);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 3), label85);

  hbox26 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox26, "hbox26");
  gtk_widget_ref (hbox26);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbox26", hbox26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (notebook3), hbox26);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox24, "vbox24");
  gtk_widget_ref (vbox24);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "vbox24", vbox24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox24);
  gtk_box_pack_start (GTK_BOX (hbox26), vbox24, TRUE, TRUE, 0);

  label101 = gtk_label_new (_("Level"));
  gtk_widget_set_name (label101, "label101");
  gtk_widget_ref (label101);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label101", label101,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (vbox24), label101, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label101), 5, 5);

  isolevel = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (700, 0, 1000, 1, 0, 0)));
  gtk_widget_set_name (isolevel, "isolevel");
  gtk_widget_ref (isolevel);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "isolevel", isolevel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (isolevel);
  gtk_box_pack_start (GTK_BOX (vbox24), isolevel, TRUE, TRUE, 0);

  label86 = gtk_label_new (_("ISO"));
  gtk_widget_set_name (label86, "label86");
  gtk_widget_ref (label86);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label86", label86,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label86);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 4), label86);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook3), empty_notebook_page);

  label87 = gtk_label_new (_("Vol"));
  gtk_widget_set_name (label87, "label87");
  gtk_widget_ref (label87);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "label87", label87,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label87);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 5), label87);

  dialog_action_area8 = GTK_DIALOG (VarGraphicsControls)->action_area;
  gtk_widget_set_name (dialog_action_area8, "dialog_action_area8");
  gtk_object_set_data (GTK_OBJECT (VarGraphicsControls), "dialog_action_area8", dialog_action_area8);
  gtk_widget_show (dialog_action_area8);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area8), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox3, "hbuttonbox3");
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (dialog_action_area8), hbuttonbox3, TRUE, TRUE, 0);

  hsliceclear = gtk_button_new_with_label (_("Clear"));
  gtk_widget_set_name (hsliceclear, "hsliceclear");
  gtk_widget_ref (hsliceclear);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hsliceclear", hsliceclear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsliceclear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), hsliceclear);
  GTK_WIDGET_SET_FLAGS (hsliceclear, GTK_CAN_DEFAULT);

  hsclose = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (hsclose, "hsclose");
  gtk_widget_ref (hsclose);
  gtk_object_set_data_full (GTK_OBJECT (VarGraphicsControls), "hsclose", hsclose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsclose);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), hsclose);
  GTK_WIDGET_SET_FLAGS (hsclose, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (VarGraphicsControls), "delete_event",
                      GTK_SIGNAL_FUNC (on_VarGraphicsControls_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Hslicebutton), "toggled",
                      GTK_SIGNAL_FUNC (on_Hslicebutton_toggled),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (Vslicebutton), "toggled",
                      GTK_SIGNAL_FUNC (on_Vslicebutton_toggled),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (CHslicebutton), "toggled",
                      GTK_SIGNAL_FUNC (on_CHslicebutton_toggled),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (hsmax), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(1));
  gtk_signal_connect (GTK_OBJECT (hsinterval), "changed",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(2));
  gtk_signal_connect (GTK_OBJECT (hsmin), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (hs_colorselect), "clicked",
                      GTK_SIGNAL_FUNC (on_colorselect_clicked),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (radiobutton1), "toggled",
                      GTK_SIGNAL_FUNC (on_linestyle_toggled),
                      GUINT_TO_POINTER(VIS5D_SOLID_LINE));
  gtk_signal_connect (GTK_OBJECT (radiobutton2), "toggled",
                      GTK_SIGNAL_FUNC (on_linestyle_toggled),
                      GUINT_TO_POINTER(VIS5D_DASHED_LINE));
  gtk_signal_connect (GTK_OBJECT (radiobutton3), "toggled",
                      GTK_SIGNAL_FUNC (on_linestyle_toggled),
                      GUINT_TO_POINTER(VIS5D_DOTTED_LINE));
  gtk_signal_connect (GTK_OBJECT (radiobutton5), "toggled",
                      GTK_SIGNAL_FUNC (on_linestyle_toggled),
                      GUINT_TO_POINTER(VIS5D_DOTDASHED_LINE));
  gtk_signal_connect (GTK_OBJECT (linewidth), "changed",
                      GTK_SIGNAL_FUNC (on_linewidth_changed),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (hlevel_vscale), "button_release_event",
                      GTK_SIGNAL_FUNC (on_level_vscale_button_release_event),
                      GINT_TO_POINTER(HSLICE));
  gtk_signal_connect (GTK_OBJECT (chsmin), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(3));
  gtk_signal_connect (GTK_OBJECT (chsmax), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(4));
  gtk_signal_connect (GTK_OBJECT (colortable_select), "clicked",
                      GTK_SIGNAL_FUNC (on_colortable_select_clicked),
                      GINT_TO_POINTER(CHSLICE));
  gtk_signal_connect (GTK_OBJECT (alpha), "button_release_event",
                      GTK_SIGNAL_FUNC (on_alpha_button_release_event),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (hs_color_sample), "leave_notify_event",
                      GTK_SIGNAL_FUNC (on_hs_color_sample_enterorleave),
                      sample_label);
  gtk_signal_connect (GTK_OBJECT (chlevel_vscale), "button_release_event",
                      GTK_SIGNAL_FUNC (on_level_vscale_button_release_event),
                      GINT_TO_POINTER(CHSLICE));
  gtk_signal_connect (GTK_OBJECT (vsmax), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(1));
  gtk_signal_connect (GTK_OBJECT (vsinterval), "changed",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(2));
  gtk_signal_connect (GTK_OBJECT (vsmin), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (vslice_move), "toggled",
                      GTK_SIGNAL_FUNC (on_vslice_move_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_colorselect_clicked),
                      GINT_TO_POINTER(2));
  gtk_signal_connect (GTK_OBJECT (spinbutton1), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (spinbutton2), "activate",
                      GTK_SIGNAL_FUNC (on_hsspin_changed),
                      GINT_TO_POINTER(1));
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_colortable_select_clicked),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (hscale1), "button_release_event",
                      GTK_SIGNAL_FUNC (on_alpha_button_release_event),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (isolevel), "button_release_event",
                      GTK_SIGNAL_FUNC (on_level_vscale_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hsliceclear), "clicked",
                      GTK_SIGNAL_FUNC (on_hsclear_clicked),
                      VarGraphicsControls);
  gtk_signal_connect (GTK_OBJECT (hsclose), "clicked",
                      GTK_SIGNAL_FUNC (on_hsclose_clicked),
                      VarGraphicsControls);

  return VarGraphicsControls;
}

