/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "window3D.h"
#include "w3D_interface.h"
#include "support.h"

GtkWidget*
create_window3D (void)
{
  GtkWidget *window3D;
  GtkWidget *vbox10;
  GtkWidget *handlebox1;
  GtkWidget *hbox14;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *open1;
  GtkWidget *open_in_new_frame1;
  GtkWidget *separator2;
  GtkWidget *delete_frame1;
  GtkWidget *exit1;
  GtkWidget *options1;
  GtkWidget *options1_menu;
  GtkAccelGroup *options1_menu_accels;
  GtkWidget *map1;
  GtkWidget *box1;
  GtkWidget *clock1;
  GtkWidget *topo1;
  GtkWidget *separator3;
  GtkWidget *view1;
  GtkWidget *view1_menu;
  GtkAccelGroup *view1_menu_accels;
  GtkWidget *top1;
  GtkWidget *south1;
  GtkWidget *separator8;
  GtkWidget *fonts1;
  GtkWidget *fonts1_menu;
  GtkAccelGroup *fonts1_menu_accels;
  GtkWidget *window_3d1;
  GtkWidget *contour_label1;
  GtkWidget *files1;
  GtkWidget *files1_menu;
  GtkAccelGroup *files1_menu_accels;
  GtkWidget *topography1;
  GtkWidget *map2;
  GtkWidget *separator6;
  GtkWidget *save_options1;
  GtkWidget *procedures1;
  GtkWidget *procedures1_menu;
  GtkAccelGroup *procedures1_menu_accels;
  GtkWidget *openprocedure;
  GtkWidget *newprocedure;
  GtkWidget *variables;
  GtkWidget *variables_menu;
  GtkAccelGroup *variables_menu_accels;
  GtkWidget *vars3D;
  GtkWidget *vars2D;
  GtkWidget *irregular;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button31;
  GtkWidget *button32;
  GtkWidget *togglebutton8;
  GtkWidget *toolbar2;
  GtkWidget *faster;
  GtkWidget *slower;
  GtkWidget *togglebutton5;
  GtkWidget *button33;
  GtkWidget *button34;
  GtkWidget *menubar2;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about1;
  GtkWidget *GtkGlArea;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window3D = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window3D, "window3D");
  gtk_object_set_data (GTK_OBJECT (window3D), "window3D", window3D);
  gtk_window_set_title (GTK_WINDOW (window3D), _("Vis5D+"));
  gtk_window_set_default_size (GTK_WINDOW (window3D), 500, 750);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox10, "vbox10");
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (window3D), vbox10);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox1, "handlebox1");
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox10), handlebox1, FALSE, TRUE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (handlebox1), hbox14);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (hbox14), menubar1, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (file1, "file1");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  open1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (open1)->child),
                                   _("_Open Data..."));
  gtk_widget_add_accelerator (open1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (open1, "open1");
  gtk_widget_ref (open1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "open1", open1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (file1_menu), open1);

  open_in_new_frame1 = gtk_menu_item_new_with_label (_("Open in new Frame..."));
  gtk_widget_set_name (open_in_new_frame1, "open_in_new_frame1");
  gtk_widget_ref (open_in_new_frame1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "open_in_new_frame1", open_in_new_frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open_in_new_frame1);
  gtk_container_add (GTK_CONTAINER (file1_menu), open_in_new_frame1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_set_name (separator2, "separator2");
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  delete_frame1 = gtk_menu_item_new_with_label (_("Delete Frame"));
  gtk_widget_set_name (delete_frame1, "delete_frame1");
  gtk_widget_ref (delete_frame1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "delete_frame1", delete_frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete_frame1);
  gtk_container_add (GTK_CONTAINER (file1_menu), delete_frame1);
  gtk_widget_set_sensitive (delete_frame1, FALSE);

  exit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit1)->child),
                                   _("E_xit Vis5d+"));
  gtk_widget_add_accelerator (exit1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit1);

  options1 = gtk_menu_item_new_with_label (_("Options"));
  gtk_widget_set_name (options1, "options1");
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (menubar1), options1);
  gtk_widget_set_sensitive (options1, FALSE);

  options1_menu = gtk_menu_new ();
  gtk_widget_set_name (options1_menu, "options1_menu");
  gtk_widget_ref (options1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "options1_menu", options1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options1), options1_menu);
  options1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (options1_menu));

  map1 = gtk_check_menu_item_new_with_label (_("Map"));
  gtk_widget_set_name (map1, "map1");
  gtk_widget_ref (map1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "map1", map1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (map1);
  gtk_container_add (GTK_CONTAINER (options1_menu), map1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (map1), TRUE);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (map1), TRUE);

  box1 = gtk_check_menu_item_new_with_label (_("Box"));
  gtk_widget_set_name (box1, "box1");
  gtk_widget_ref (box1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "box1", box1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (box1);
  gtk_container_add (GTK_CONTAINER (options1_menu), box1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (box1), TRUE);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (box1), TRUE);

  clock1 = gtk_check_menu_item_new_with_label (_("Clock"));
  gtk_widget_set_name (clock1, "clock1");
  gtk_widget_ref (clock1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "clock1", clock1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clock1);
  gtk_container_add (GTK_CONTAINER (options1_menu), clock1);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (clock1), TRUE);

  topo1 = gtk_check_menu_item_new_with_label (_("Topo"));
  gtk_widget_set_name (topo1, "topo1");
  gtk_widget_ref (topo1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "topo1", topo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (topo1);
  gtk_container_add (GTK_CONTAINER (options1_menu), topo1);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (topo1), TRUE);

  separator3 = gtk_menu_item_new ();
  gtk_widget_set_name (separator3, "separator3");
  gtk_widget_ref (separator3);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "separator3", separator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (options1_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  view1 = gtk_menu_item_new_with_label (_("View"));
  gtk_widget_set_name (view1, "view1");
  gtk_widget_ref (view1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "view1", view1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view1);
  gtk_container_add (GTK_CONTAINER (options1_menu), view1);

  view1_menu = gtk_menu_new ();
  gtk_widget_set_name (view1_menu, "view1_menu");
  gtk_widget_ref (view1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "view1_menu", view1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view1), view1_menu);
  view1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (view1_menu));

  top1 = gtk_menu_item_new_with_label (_("Top"));
  gtk_widget_set_name (top1, "top1");
  gtk_widget_ref (top1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "top1", top1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (top1);
  gtk_container_add (GTK_CONTAINER (view1_menu), top1);

  south1 = gtk_menu_item_new_with_label (_("South"));
  gtk_widget_set_name (south1, "south1");
  gtk_widget_ref (south1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "south1", south1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (south1);
  gtk_container_add (GTK_CONTAINER (view1_menu), south1);

  separator8 = gtk_menu_item_new ();
  gtk_widget_set_name (separator8, "separator8");
  gtk_widget_ref (separator8);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "separator8", separator8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator8);
  gtk_container_add (GTK_CONTAINER (options1_menu), separator8);
  gtk_widget_set_sensitive (separator8, FALSE);

  fonts1 = gtk_menu_item_new_with_label (_("Fonts"));
  gtk_widget_set_name (fonts1, "fonts1");
  gtk_widget_ref (fonts1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "fonts1", fonts1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fonts1);
  gtk_container_add (GTK_CONTAINER (options1_menu), fonts1);

  fonts1_menu = gtk_menu_new ();
  gtk_widget_set_name (fonts1_menu, "fonts1_menu");
  gtk_widget_ref (fonts1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "fonts1_menu", fonts1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (fonts1), fonts1_menu);
  fonts1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (fonts1_menu));

  window_3d1 = gtk_menu_item_new_with_label (_("Window 3D"));
  gtk_widget_set_name (window_3d1, "window_3d1");
  gtk_widget_ref (window_3d1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "window_3d1", window_3d1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (window_3d1);
  gtk_container_add (GTK_CONTAINER (fonts1_menu), window_3d1);
  gtk_tooltips_set_tip (tooltips, window_3d1, _("Select the default font for 3D Graphics labels"), NULL);

  contour_label1 = gtk_menu_item_new_with_label (_("Contour Label"));
  gtk_widget_set_name (contour_label1, "contour_label1");
  gtk_widget_ref (contour_label1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "contour_label1", contour_label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (contour_label1);
  gtk_container_add (GTK_CONTAINER (fonts1_menu), contour_label1);
  gtk_tooltips_set_tip (tooltips, contour_label1, _("Select the contour label font "), NULL);

  files1 = gtk_menu_item_new_with_label (_("Files"));
  gtk_widget_set_name (files1, "files1");
  gtk_widget_ref (files1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "files1", files1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (files1);
  gtk_container_add (GTK_CONTAINER (options1_menu), files1);

  files1_menu = gtk_menu_new ();
  gtk_widget_set_name (files1_menu, "files1_menu");
  gtk_widget_ref (files1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "files1_menu", files1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (files1), files1_menu);
  files1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (files1_menu));

  topography1 = gtk_menu_item_new_with_label (_("Topography"));
  gtk_widget_set_name (topography1, "topography1");
  gtk_widget_ref (topography1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "topography1", topography1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (topography1);
  gtk_container_add (GTK_CONTAINER (files1_menu), topography1);

  map2 = gtk_menu_item_new_with_label (_("Map"));
  gtk_widget_set_name (map2, "map2");
  gtk_widget_ref (map2);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "map2", map2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (map2);
  gtk_container_add (GTK_CONTAINER (files1_menu), map2);

  separator6 = gtk_menu_item_new ();
  gtk_widget_set_name (separator6, "separator6");
  gtk_widget_ref (separator6);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "separator6", separator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator6);
  gtk_container_add (GTK_CONTAINER (options1_menu), separator6);
  gtk_widget_set_sensitive (separator6, FALSE);

  save_options1 = gtk_menu_item_new_with_label (_("Save Options"));
  gtk_widget_set_name (save_options1, "save_options1");
  gtk_widget_ref (save_options1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "save_options1", save_options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_options1);
  gtk_container_add (GTK_CONTAINER (options1_menu), save_options1);

  procedures1 = gtk_menu_item_new_with_label (_("Procedures"));
  gtk_widget_set_name (procedures1, "procedures1");
  gtk_widget_ref (procedures1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "procedures1", procedures1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (procedures1);
  gtk_container_add (GTK_CONTAINER (menubar1), procedures1);
  gtk_widget_set_sensitive (procedures1, FALSE);

  procedures1_menu = gtk_menu_new ();
  gtk_widget_set_name (procedures1_menu, "procedures1_menu");
  gtk_widget_ref (procedures1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "procedures1_menu", procedures1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (procedures1), procedures1_menu);
  procedures1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (procedures1_menu));

  openprocedure = gtk_menu_item_new_with_label (_("Open"));
  gtk_widget_set_name (openprocedure, "openprocedure");
  gtk_widget_ref (openprocedure);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "openprocedure", openprocedure,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (openprocedure);
  gtk_container_add (GTK_CONTAINER (procedures1_menu), openprocedure);

  newprocedure = gtk_menu_item_new_with_label (_("New"));
  gtk_widget_set_name (newprocedure, "newprocedure");
  gtk_widget_ref (newprocedure);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "newprocedure", newprocedure,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newprocedure);
  gtk_container_add (GTK_CONTAINER (procedures1_menu), newprocedure);

  variables = gtk_menu_item_new_with_label (_("Variables"));
  gtk_widget_set_name (variables, "variables");
  gtk_widget_ref (variables);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "variables", variables,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (variables);
  gtk_container_add (GTK_CONTAINER (menubar1), variables);
  gtk_widget_set_sensitive (variables, FALSE);

  variables_menu = gtk_menu_new ();
  gtk_widget_set_name (variables_menu, "variables_menu");
  gtk_widget_ref (variables_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "variables_menu", variables_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (variables), variables_menu);
  variables_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (variables_menu));

  vars3D = gtk_menu_item_new_with_label (_("3D"));
  gtk_widget_set_name (vars3D, "vars3D");
  gtk_widget_ref (vars3D);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "vars3D", vars3D,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_container_add (GTK_CONTAINER (variables_menu), vars3D);
  gtk_widget_set_sensitive (vars3D, FALSE);

  vars2D = gtk_menu_item_new_with_label (_("2D"));
  gtk_widget_set_name (vars2D, "vars2D");
  gtk_widget_ref (vars2D);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "vars2D", vars2D,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_container_add (GTK_CONTAINER (variables_menu), vars2D);
  gtk_widget_set_sensitive (vars2D, FALSE);

  irregular = gtk_menu_item_new_with_label (_("Irregular"));
  gtk_widget_set_name (irregular, "irregular");
  gtk_widget_ref (irregular);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "irregular", irregular,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_container_add (GTK_CONTAINER (variables_menu), irregular);
  gtk_widget_set_sensitive (irregular, FALSE);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox14), toolbar1, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (toolbar1, FALSE);

  tmp_toolbar_icon = create_pixmap (window3D, "first.xpm");
  button31 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("First"),
                                _("Display first frame."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button31, "button31");
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);

  tmp_toolbar_icon = create_pixmap (window3D, "left.xpm");
  button32 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Previous"),
                                _("Display previous frame."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button32, "button32");
  gtk_widget_ref (button32);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "button32", button32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button32);

  tmp_toolbar_icon = create_pixmap (window3D, "animate_backward.xpm");
  togglebutton8 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Animate"),
                                _("Toggle backward animation.  "), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (togglebutton8, "togglebutton8");
  gtk_widget_ref (togglebutton8);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "togglebutton8", togglebutton8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (togglebutton8);

  toolbar2 = gtk_toolbar_new (GTK_ORIENTATION_VERTICAL, GTK_TOOLBAR_ICONS);
  gtk_widget_set_name (toolbar2, "toolbar2");
  gtk_widget_ref (toolbar2);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "toolbar2", toolbar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar2);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), toolbar2, NULL, NULL);

  tmp_toolbar_icon = create_pixmap (window3D, "up.xpm");
  faster = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button35"),
                                _("animate faster"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (faster, "faster");
  gtk_widget_ref (faster);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "faster", faster,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faster);
  gtk_widget_set_sensitive (faster, FALSE);

  tmp_toolbar_icon = create_pixmap (window3D, "down.xpm");
  slower = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button36"),
                                _("animate slower"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (slower, "slower");
  gtk_widget_ref (slower);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "slower", slower,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (slower);
  gtk_widget_set_sensitive (slower, FALSE);

  tmp_toolbar_icon = create_pixmap (window3D, "animate_forward.xpm");
  togglebutton5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Animate"),
                                _("Toggle forward animation.  "), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (togglebutton5, "togglebutton5");
  gtk_widget_ref (togglebutton5);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "togglebutton5", togglebutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (togglebutton5);

  tmp_toolbar_icon = create_pixmap (window3D, "right.xpm");
  button33 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Next"),
                                _("Display next frame."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button33, "button33");
  gtk_widget_ref (button33);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "button33", button33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button33);

  tmp_toolbar_icon = create_pixmap (window3D, "last.xpm");
  button34 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Last"),
                                _("Display final frame."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button34, "button34");
  gtk_widget_ref (button34);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "button34", button34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button34);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar2, "menubar2");
  gtk_widget_ref (menubar2);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "menubar2", menubar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar2);
  gtk_box_pack_start (GTK_BOX (hbox14), menubar2, FALSE, FALSE, 0);

  help1 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_set_name (help1, "help1");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar2), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about1 = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  GtkGlArea = create_glarea ("GtkGlArea", NULL, NULL, 0, 0);
  gtk_widget_set_name (GtkGlArea, "GtkGlArea");
  gtk_widget_ref (GtkGlArea);
  gtk_object_set_data_full (GTK_OBJECT (window3D), "GtkGlArea", GtkGlArea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkGlArea);
  gtk_box_pack_start (GTK_BOX (vbox10), GtkGlArea, TRUE, TRUE, 0);
  gtk_widget_set_usize (GtkGlArea, -2, 400);
  GTK_WIDGET_UNSET_FLAGS (GtkGlArea, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (GtkGlArea, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (open1), "activate",
                      GTK_SIGNAL_FUNC (on_open1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (open_in_new_frame1), "activate",
                      GTK_SIGNAL_FUNC (on_open_in_new_frame1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (delete_frame1), "activate",
                      GTK_SIGNAL_FUNC (on_delete_frame1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (map1), "activate",
                      GTK_SIGNAL_FUNC (on_map1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (box1), "activate",
                      GTK_SIGNAL_FUNC (on_box1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clock1), "activate",
                      GTK_SIGNAL_FUNC (on_clock1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (topo1), "activate",
                      GTK_SIGNAL_FUNC (on_topo1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (top1), "activate",
                      GTK_SIGNAL_FUNC (on_setview_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (south1), "activate",
                      GTK_SIGNAL_FUNC (on_setview_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (window_3d1), "activate",
                      GTK_SIGNAL_FUNC (on_window_3d1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (contour_label1), "activate",
                      GTK_SIGNAL_FUNC (on_contour_label1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (topography1), "activate",
                      GTK_SIGNAL_FUNC (on_topography1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (map2), "activate",
                      GTK_SIGNAL_FUNC (on_map2_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_options1), "activate",
                      GTK_SIGNAL_FUNC (on_save_options1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (openprocedure), "activate",
                      GTK_SIGNAL_FUNC (on_openprocedure_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newprocedure), "activate",
                      GTK_SIGNAL_FUNC (on_newprocedure_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (vars3D), "activate",
                      GTK_SIGNAL_FUNC (on_vars3D_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (vars2D), "activate",
                      GTK_SIGNAL_FUNC (on_vars2D_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (irregular), "activate",
                      GTK_SIGNAL_FUNC (on_irregular_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button31), "clicked",
                      GTK_SIGNAL_FUNC (on_Arrow_clicked),
                      "first");
  gtk_signal_connect (GTK_OBJECT (button32), "clicked",
                      GTK_SIGNAL_FUNC (on_Arrow_clicked),
                      "previous");
  gtk_signal_connect (GTK_OBJECT (togglebutton8), "toggled",
                      GTK_SIGNAL_FUNC (on_animate_toggled),
                      "backward");
  gtk_signal_connect (GTK_OBJECT (faster), "clicked",
                      GTK_SIGNAL_FUNC (on_change_animate_speed),
                      GINT_TO_POINTER(1));
  gtk_signal_connect (GTK_OBJECT (slower), "clicked",
                      GTK_SIGNAL_FUNC (on_change_animate_speed),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (togglebutton5), "toggled",
                      GTK_SIGNAL_FUNC (on_animate_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button33), "clicked",
                      GTK_SIGNAL_FUNC (on_Arrow_clicked),
                      "next");
  gtk_signal_connect (GTK_OBJECT (button34), "clicked",
                      GTK_SIGNAL_FUNC (on_Arrow_clicked),
                      "last");
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkGlArea), "button_release_event",
                      GTK_SIGNAL_FUNC (glarea_button_release),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkGlArea), "button_press_event",
                      GTK_SIGNAL_FUNC (glarea_button_press),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkGlArea), "motion_notify_event",
                      GTK_SIGNAL_FUNC (glarea_motion_notify),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkGlArea), "expose_event",
                      GTK_SIGNAL_FUNC (glarea_draw),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkGlArea), "configure_event",
                      GTK_SIGNAL_FUNC (glarea_reshape),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkGlArea), "realize",
                      GTK_SIGNAL_FUNC (glarea_init),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (window3D), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (window3D), accel_group);

  return window3D;
}

